
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JorgeLuis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        productos = new JComboBox();
        cajeros = new JComboBox();
        porComprar = new ArrayList();
        traerCajeros();
        traerProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_admin = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombreCaj = new javax.swing.JTextField();
        jt_ID = new javax.swing.JFormattedTextField();
        jb_crearCajero = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nameProduct = new javax.swing.JTextField();
        sp_tiempo = new javax.swing.JSpinner();
        tf_precio = new javax.swing.JTextField();
        jb_crearPro = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jl_cajero = new javax.swing.JLabel();
        jl_cliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_producto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jd_cliente = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nameClient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jb_agregarProducto = new javax.swing.JButton();
        jb_comprar = new javax.swing.JButton();
        productoss = new javax.swing.JComboBox<>();
        cajeross = new javax.swing.JComboBox<>();
        jb_salir2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jb_admin = new javax.swing.JButton();
        jb_cliente = new javax.swing.JButton();

        jLabel2.setText("Nombre");

        jLabel3.setText("ID");

        try {
            jt_ID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jb_crearCajero.setText("Crear");
        jb_crearCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCajeroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_crearCajero)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombreCaj)
                            .addComponent(jt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_nombreCaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jb_crearCajero)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Cajero", jPanel1);

        jLabel5.setText("Nombre");

        jLabel6.setText("Precio");

        jLabel7.setText("Tiempo de Prcesamiento");

        jb_crearPro.setText("Crear");
        jb_crearPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearProMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52)
                                .addComponent(sp_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nameProduct)
                                    .addComponent(tf_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jb_crearPro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(sp_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jb_crearPro)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Producto", jPanel2);

        jb_salir.setText("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_adminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_salir)
                .addGap(40, 40, 40))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_adminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jl_cajero.setText("nameCajero");

        jl_cliente.setText("nameCliente");

        jLabel4.setText("Procesando");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cliente", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jl_cajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_cliente)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addComponent(tf_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cajero)
                    .addComponent(jl_cliente))
                .addGap(32, 32, 32)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel8.setText("Cliente");

        jLabel9.setText("Nombre");

        jLabel10.setText("Edad");

        jb_agregarProducto.setText("Agregar a Orden");
        jb_agregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarProductoMouseClicked(evt);
            }
        });

        jb_comprar.setText("Realizar Compra");
        jb_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_comprarMouseClicked(evt);
            }
        });
        jb_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_comprarActionPerformed(evt);
            }
        });

        productoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productossActionPerformed(evt);
            }
        });

        jb_salir2.setText("Salir");
        jb_salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salir2MouseClicked(evt);
            }
        });

        jLabel11.setText("Producto");

        jLabel12.setText("Cajero");

        javax.swing.GroupLayout jd_clienteLayout = new javax.swing.GroupLayout(jd_cliente.getContentPane());
        jd_cliente.getContentPane().setLayout(jd_clienteLayout);
        jd_clienteLayout.setHorizontalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_clienteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(43, 43, 43)
                                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_clienteLayout.createSequentialGroup()
                                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                                .addComponent(jb_salir2))))
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_agregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productoss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addComponent(cajeross, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_clienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_comprar)
                .addGap(36, 36, 36))
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(86, 86, 86))
        );
        jd_clienteLayout.setVerticalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jb_salir2))
                .addGap(48, 48, 48)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajeross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jb_agregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_comprar)
                .addGap(13, 13, 13))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Super Mercado");

        jb_admin.setText("Administrador");
        jb_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_adminMouseClicked(evt);
            }
        });

        jb_cliente.setText("Cliente");
        jb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_admin))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jb_admin)
                .addGap(35, 35, 35)
                .addComponent(jb_cliente)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearCajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCajeroMouseClicked
        try {
            if (!this.jt_nombreCaj.getText().equals("")) {
                if (IDUnico(this.jt_ID.getText())) {
                    Cajero c = new Cajero(this.jt_nombreCaj.getText(), this.jt_ID.getText());
                    DefaultComboBoxModel model = (DefaultComboBoxModel) cajeross.getModel();
                    model.addElement(c);
                    this.jt_ID.setText("");
                    this.jt_nombreCaj.setText("");
                    c.getFrame().setVisible(true);
                    ((PantallaProceso) c.getFrame()).getJl_cajero().setText("Cajero: " + c.getNombre());
                }else{
                    JOptionPane.showMessageDialog(this.jd_admin, "El ID debe ser único");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se creó el Cajero");
        }
    }//GEN-LAST:event_jb_crearCajeroMouseClicked

    private void jb_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_adminMouseClicked
        this.setVisible(false);
        this.jd_admin.pack();
        this.jd_admin.setVisible(true);
        this.jd_admin.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_adminMouseClicked

    private void jb_crearProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearProMouseClicked
        try {
            if (!this.tf_nameProduct.getText().equals("")) {
                if (!this.tf_precio.getText().equals("")) {
                    if ((int) this.sp_tiempo.getValue() > 0) {
                        Producto p = new Producto(this.tf_nameProduct.getText(), Float.parseFloat(this.tf_precio.getText()), (int) this.sp_tiempo.getValue());
                        DefaultComboBoxModel model = (DefaultComboBoxModel) productoss.getModel();
                        model.addElement(p);
                        this.tf_nameProduct.setText("");
                        this.tf_precio.setText("");
                        this.sp_tiempo.setValue(3);
                    } else {
                        JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se creó el Producto");
        }
    }//GEN-LAST:event_jb_crearProMouseClicked

    private void jb_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_comprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_comprarActionPerformed

    private void productossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productossActionPerformed

    private void jb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clienteMouseClicked
        this.jd_cliente.setVisible(true);
        this.setVisible(false);
        this.jd_cliente.pack();
        this.jd_cliente.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_clienteMouseClicked

    private void jb_salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salir2MouseClicked
        this.setVisible(true);
        this.jd_cliente.setVisible(false);
        regresarProductos();
    }//GEN-LAST:event_jb_salir2MouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        this.setVisible(true);
        this.jd_admin.setVisible(false);
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_agregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarProductoMouseClicked
        DefaultComboBoxModel model = (DefaultComboBoxModel) productoss.getModel();
        porComprar.add((Producto) model.getSelectedItem());
        model.removeElement(model.getSelectedItem());
        productoss.setModel(model);
    }//GEN-LAST:event_jb_agregarProductoMouseClicked

    private void jb_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_comprarMouseClicked
        try {
            if (!this.tf_nameClient.getText().equals("")) {
                Client c = new Client(this.tf_nameClient.getText(), (int) this.sp_edad.getValue());
                DefaultComboBoxModel caj = (DefaultComboBoxModel) this.cajeross.getModel();
                Orden o = new Orden((Cajero) caj.getSelectedItem(), c, porComprar);
                ((Cajero) caj.getSelectedItem()).getOrdenes().add(o);
                if (!((Cajero) caj.getSelectedItem()).isRunning()) {
                    ((Cajero) caj.getSelectedItem()).start();
                }
                porComprar = new ArrayList();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.jd_cliente, "Ocurrió un error y no se realizó la compra");
            e.printStackTrace();
            porComprar = new ArrayList();
            regresarProductos();
        }
    }//GEN-LAST:event_jb_comprarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cajeross;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_admin;
    private javax.swing.JButton jb_agregarProducto;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JButton jb_comprar;
    private javax.swing.JButton jb_crearCajero;
    private javax.swing.JButton jb_crearPro;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salir2;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_cliente;
    private javax.swing.JLabel jl_cajero;
    private javax.swing.JLabel jl_cliente;
    private javax.swing.JFormattedTextField jt_ID;
    private javax.swing.JTextField jt_nombreCaj;
    private javax.swing.JComboBox<String> productoss;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_tiempo;
    private javax.swing.JTextField tf_nameClient;
    private javax.swing.JTextField tf_nameProduct;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_producto;
    // End of variables declaration//GEN-END:variables
JComboBox cajeros;
    JComboBox productos;
    ArrayList<Producto> porComprar;

    public void regresarProductos() {
        for (Producto producto : porComprar) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) productoss.getModel();
            ArrayList<Producto> comparar = new ArrayList();
            for (int x = 0; x < model.getSize(); x++) {
                comparar.add((Producto) model.getElementAt(x));
            }
            if (!comparar.contains(producto)) {
                model.addElement(producto);
            }
        }
    }

    public void traerCajeros() {

    }

    public void traerProductos() {

    }

    public boolean IDUnico(String ID) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cajeross.getModel();
        for (int x = 0; x < model.getSize(); x++) {
            if (((Cajero) model.getElementAt(x)).getID().equals(ID)) {
                return false;
            }
        }
        return true;
    }
}
